name: Terraform Destroy
on: workflow_dispatch
env:
  AWS_SECRET_KEY_ID: ${{secrets.AWS_SECRET_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  TFVAR_aws_pub_key: ${{secrets.AWS_PUBLIC_KEY}}

jobs:
  terraform:
    name: terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set Date
      run: date
    - name: Terraform Init
      run: terraform init -backend-config="access_key=secrets.$AWS_SECRET_KEY_ID" -backend-config="secret_key=$AWS_SECRET_ACCESS_KEY" -backend-config="region=sa-east-1" 
    - name: Terraform Validate
      run: terraform validate
    - name: Terraform Destroy
      run: terraform destroy -auto-approve